<div class="sqlme-notice">
    Here you can see list of your database tables, it's engines and rows counts per table.
    By default we provide rows amount only for MyISAM tables because they store rows amount as table metadata information.
    In turn, InnoDB require rows evaluation which can lead to extra loading on a big tables.
    For such tables you must click arrow icon to obtain rows count.
</div>
<table width="100%" id="sqlme-table">
    <tr>
        <th align="left">Table name</th>
        <th>Engine</th>
        <th>Rows number</th>
        <th class="sqlme-refresh-cell"><img src="/wp-content/plugins/SqlMe/public/img/refresh.png" /></th>
    </tr>
    <?php foreach ($this->tables as $table): ?>
    <tr class="sqlme-data-rows">
        <td><?php echo $table['name'] ?></td>
        <td align="center"><?php echo $table['engine'] ?></td>
        <td align="center" class="sqlme-amount-cell"><?php echo $table['amount'] ?></td>
        <td align="center" class="sqlme-refresh-cell"><img src="/wp-content/plugins/SqlMe/public/img/refresh.png" /></td>
    </tr>
    <?php endforeach ?>
    <tr>
        <td colspan="2"></td>
        <td align="center" id="sqlme-total-amount"><?php echo $this->totalAmount ?></td>
        <th class="sqlme-refresh-cell"><img src="/wp-content/plugins/SqlMe/public/img/refresh.png" /></th>
    </tr>
</table>
<script>
jQuery(document).ready(function() {
    jQuery(".sqlme-refresh-cell img").click(function(e) {
        var cell = jQuery(this).parent();
        switch (cell.prop("tagName").toLowerCase()) {
            case "th": {
                jQuery("#sqlme-table").find("tr.sqlme-data-rows").each(function() {
                    jQuery(this).find("td:last img").trigger("click");
                })
            } break;
            case "td": {
                var tableName  = cell.parent().find("td:first-child").text()
                var amountCell = cell.prev();
                var mask = Mask.show(amountCell);

                function createCallback(mask) {
                    return function() {
                        mask.hide();
                        var cells = jQuery("#sqlme-table .sqlme-amount-cell");
                        var values = jQuery.map(cells, function(cell) {
                            var value = jQuery(cell).text();
                            if (jQuery.isNumeric(value)) {
                                return parseInt(value);
                            } else {
                                return 0;
                            }
                        })
                        jQuery("#sqlme-total-amount").text(values.reduce(function(pv, cv) {
                            return pv + cv;
                        }, 0));
                    }
                }

                var url = "/wp-admin/admin-ajax.php?action=sqlme_tables_count&table=" + tableName
                amountCell.load(url, {}, createCallback(mask))
            }
        }
    })
});
</script>